---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component takes a stream of JSON messages from StreamManager and batches them into a gzip file. It uses a JSON Line (JSONL) format for the messages."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.StreamManager:
    VersionRequirement: "^2.0.0"
    DependencyType: "HARD"
ComponentConfiguration:
  DefaultConfiguration:
    StreamName: "BatchMessageStream"
    BatchSize: "20"
    OutputFolder: "gzip"
    Interval: "30"
    LogLevel: "INFO"
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/aws-greengrass-json-gzip.zip"
        Unarchive: ZIP
    Lifecycle:
      Run: "python3 -u {artifacts:decompressedPath}/aws-greengrass-json-gzip/main.py \"{configuration:/StreamName}\" \"{configuration:/BatchSize}\" \"{configuration:/OutputFolder}\" \"{configuration:/Interval}\" \"{configuration:/LogLevel}\""
      Install: "pip3 install --user -r {artifacts:decompressedPath}/aws-greengrass-json-gzip/requirements.txt"
