---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component takes a stream of JSON messages from StreamManager and batches them into a gzip file. It uses a JSON Line (JSONL) format for the messages."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.StreamManager:
    VersionRequirement: "^2.0.0"
    DependencyType: "HARD"
ComponentConfiguration:
  DefaultConfiguration:
    Processor:
      StreamName: "BatchMessageStream"
      BatchSize: "20"
      Interval: "30"
      Path: "/tmp/greengrass/gzip"
    Uploader:
      BucketName: "<PLACEHOLDER BUCKET HERE>"
      Interval: "1"
      Path: "/tmp/greengrass/gzip/*"
    LogLevel: "INFO"
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/aws-greengrass-json-gzip.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: 
        Script: |-
          pip3 install --user -r {artifacts:decompressedPath}/aws-greengrass-json-gzip/requirements.txt
      Run: 
        Script: |-
          python3 -u {artifacts:decompressedPath}/aws-greengrass-json-gzip/main.py "{configuration:/Processor/StreamName}" "{configuration:/Processor/BatchSize}" "{configuration:/Processor/Interval}" "{configuration:/Processor/Path}" "{configuration:/Uploader/BucketName}" "{configuration:/Uploader/Interval}" "{configuration:/Uploader/Path}" "{configuration:/LogLevel}"
